### ISSUE TITLE
Sensors - LSM6DSOX Basic features

### ISSUE THREAD

**Issue by YannLocatelli** [leka/LekaOS_Explorations#11]
Based on issue https://github.com/leka/LekaOS_Explorations/issues/9

## Sub-tasks
 
* [x] i2c connection
* [x] get ID
* [x] get device status
* [x] get device interrupt status
* [x] get data

**Comment by YannLocatelli** [comment]
Ajout:

* [x] get device interrupt status

**Comment by ladislas** [comment]
c'est quoi le interrupt status?

**Comment by YannLocatelli** [comment]
C'est par exemple un `dataReady` qui fait partie des interrupts
